FROM node:latest

# Définir le répertoire de travail dans le conteneur
WORKDIR /Keccak_Challenge

# Copier le reste des fichiers de l'application
COPY ./Keccak_Challenge .

# Installer les dépendances
RUN npm install

# Exposer le port sur lequel le serveur va écouter
EXPOSE 3000

# Commande pour démarrer l'application
CMD ["node", "src/app.js"]