version: "3"
services:
  backend:
    build:
      context: ./ # Chemin vers le dossier contenant le Dockerfile du back-end
      dockerfile: Dockerfile.back
    image: keccak_back:latest
    ports:
      - "4021:3000" # Mapper le port du conteneur à un port sur la machine hôte
    depends_on:
      - frontend # S'assurer que le conteneur du front-end démarre avant celui du back-end

  frontend:
    build:
      context: ./ # Chemin vers le dossier contenant le Dockerfile du front-end
      dockerfile: Dockerfile.front
    image: keccak_front:latest
    ports:
      - "4022:80" # Mapper le port du conteneur à un port sur la machine hôte
